# Generated by Django 3.0.2 on 2020-03-12 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=11)),
                ('address_line_1', models.CharField(blank=True, default='', max_length=40)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=40)),
                ('town_city', models.CharField(blank=True, default='', max_length=40)),
                ('county', models.CharField(blank=True, default='', max_length=40)),
                ('country', models.CharField(blank=True, default='', max_length=40)),
                ('postcode', models.CharField(blank=True, default='', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
