# Generated by Django 2.2.5 on 2019-11-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_orders_price'),
        ('checkout', '0002_auto_20191108_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.Orders'),
        ),
    ]
