# Generated by Django 3.0 on 2019-12-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_entries_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='product',
        ),
    ]
