# Generated by Django 3.0 on 2019-12-27 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('checkout', '0004_remove_entries_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='competition_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Competition'),
        ),
    ]
