# Generated by Django 3.0.2 on 2020-03-12 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.IntegerField(default=4000)),
                ('tickets_left', models.IntegerField(default=4000)),
                ('question', models.CharField(default='Question', max_length=200)),
                ('answer_1', models.CharField(default='Answer 1', max_length=200)),
                ('answer_2', models.CharField(default='Answer 2', max_length=200)),
                ('answer_3', models.CharField(default='Answer 3', max_length=200)),
                ('correct_answer', models.CharField(default='Correct Answer', max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('next_competition', models.BooleanField(default=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.Entries')),
            ],
        ),
    ]
