# Generated by Django 2.2.5 on 2019-11-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20191108_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_answer',
            field=models.BooleanField(default=False),
        ),
    ]
