# Generated by Django 2.2.5 on 2019-11-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orders_user_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user_answer',
            new_name='user_answer_correct',
        ),
    ]
