# Generated by Django 3.0.2 on 2020-03-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_orderitem_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='answer_correct',
            field=models.BooleanField(default=False),
        ),
    ]
