# Generated by Django 3.0.2 on 2020-05-04 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_coupons', '0001_initial'),
        ('cart', '0005_order_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_simple_coupons.Coupon'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
