# Generated by Django 2.2.5 on 2019-11-08 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='Make', max_length=50)),
                ('model', models.CharField(default='Model', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('img', models.ImageField(default='default.jpg', upload_to='')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product_link', models.URLField(default='#')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Categories')),
                ('fits', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Vehicle')),
            ],
        ),
    ]
