# Generated by Django 2.2.5 on 2019-12-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191201_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='generation',
            field=models.CharField(default='', max_length=15),
        ),
    ]
