# Generated by Django 3.0 on 2020-01-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_vehicle_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fits_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Manufacturer'),
        ),
    ]
