# Generated by Django 3.2.7 on 2021-10-03 20:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
