# Generated by Django 3.0 on 2020-01-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200103_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='part_manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Manufacturer'),
        ),
    ]
