# Generated by Django 3.0.2 on 2020-03-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200129_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fits',
        ),
        migrations.AddField(
            model_name='product',
            name='fits',
            field=models.ManyToManyField(blank=True, null=True, to='products.Vehicle'),
        ),
    ]
