# Generated by Django 3.0.2 on 2020-03-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200303_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fits',
            field=models.ManyToManyField(to='products.Vehicle'),
        ),
    ]
