# Generated by Django 3.0.2 on 2020-03-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200303_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fits_multiple',
        ),
    ]
