# Generated by Django 3.0.2 on 2020-03-03 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_fits_multiple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fits',
        ),
        migrations.CreateModel(
            name='Fitments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Vehicle')),
            ],
        ),
    ]
